# CocoaPods test project
# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'TestCocoaPodsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pod dependencies for testing
  pod 'AFNetworking', '~> 4.0'
  pod 'Alamofire', '~> 5.6'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'SnapKit', '~> 5.6'
  
  # Development pods
  pod 'SwiftLint', '~> 0.50', :configurations => ['Debug']
  
  target 'TestCocoaPodsAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick', '~> 5.0'
    pod 'Nimble', '~> 10.0'
  end

  target 'TestCocoaPodsAppUITests' do
    # Pods for testing
  end

end

# Post-install hooks
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end