workspace:
  name: test-semantic-search
  root_path: /Users/y-hirakawa/git/effortlessly-mcp/test-semantic-search-project-ts
  created_at: '2025-08-18T13:34:51.359Z'
  last_accessed: '2025-08-18T13:34:51.375Z'
  settings:
    index_enabled: true
    lsp_servers:
      - typescript
    auto_save_logs: false
    log_retention_days: 1
    max_file_size: 1048576
    excluded_patterns:
      - '*.env'
      - '*.key'
      - '*.pem'
      - node_modules/**
      - .git/**
    follow_symlinks: false
logging:
  operations:
    enabled: false
  diff:
    enabled: true
    max_lines_for_detailed_diff: 500
    display_options:
      default_context_lines: 3
lsp_servers:
  proxy_server:
    enabled: true
    host: localhost
    port: 3001
    auto_start: true
    startup_timeout: 10000
  supported_languages:
    typescript:
      enabled: true
      server_command: typescript-language-server
      server_args:
        - '--stdio'
    python:
      enabled: false
      server_command: pylsp
      server_args: []
    swift:
      enabled: false
      server_command: sourcekit-lsp
      server_args: []
